base_url = "https://mrioqueiroz.com"
title = "Mário Queiroz"
description = "Personal Blog"
theme = "terminimal"
minify_html = true
compile_sass = true
highlight_code = true
highlight_theme = "gruvbox-dark"
build_search_index = true

[extra]
accent_color = "blue"
background_color = "light"
logo_text = "Mário Queiroz"
author = "Mário Queiroz"
use_full_hack_font = true
enable_post_view_navigation = true
post_view_navigation_prompt = "Read more"
menu_items = [
    {name = "linkedin", url = "https://linkedin.com/in/mrioqueiroz", newtab = true},
    {name = "twitter", url = "https://twitter.com/mrioqueiroz", newtab = true},
    {name = "github", url = "https://github.com/mrioqueiroz", newtab = true},
    {name = "source code", url = "https://github.com/mrioqueiroz/nix-hosts", newtab = true},
    {name = "buy me a coffee", url = "https://buymeacoffee.com/mrioqueiroz", newtab = true},
]
