base_url = "https://mrioqueiroz.com"

compile_sass = true

# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

build_search_index = true

theme = "terminimal"

[extra]
accent_color = "blue"
background_color = "dark"
logo_text = "Mário Queiroz"
author = "Mário Queiroz"
use_full_hack_font = true
enable_post_view_navigation = true
post_view_navigation_prompt = "Read more"
