base_url = "https://mrioqueiroz.com"
title = "M치rio Queiroz"
description = "Personal Blog"
theme = "zerm"

# New lines are being removed from code blocks if this is enabled.
# See: https://github.com/getzola/zola/issues/1300
minify_html = false
compile_sass = true
build_search_index = true

taxonomies = [
  {name = "tags"},
  {name = "categories"},
]

[markdown]
highlight_code = true
highlight_theme = "gruvbox-dark"

[extra]
theme_color = "orange"
logo_text = "M치rio Queiroz"
author = "M치rio Queiroz"
copyright = "M치rio Queiroz"
show_author = false
center = true
show_tags = true
show_categories = true
enable_post_view_navigation = true
post_view_navigation_prompt = "read more"
full_width = false
show_menu_items = 0
menu_more = "info"
read_more = "read more"

main_menu = [
  {name = "about", url = "/what-is-this-all-about"},
  {name = "GitHub", url = "https://github.com/mrioqueiroz", external = true},
  {name = "LinkedIn", url = "https://linkedin.com/in/mrioqueiroz", external = true},
]
